# Generated by Django 2.2 on 2019-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='fecha_peticion')),
            ],
        ),
    ]
